// This file is auto-generated by @hey-api/openapi-ts

export type AdvisoryDetails = AdvisoryHead &
  (null | SourceDocument) & {
    /**
     * Average (arithmetic mean) score of the advisory aggregated from *all* related vulnerability assertions.
     */
    average_score: number | null;
    average_severity: null | Severity;
    /**
     * Vulnerabilities addressed within this advisory.
     */
    vulnerabilities: Array<AdvisoryVulnerabilitySummary>;
  };

export type AdvisoryHead = {
  /**
   * The identifier of the advisory, as provided by the document.
   */
  document_id: string;
  /**
   * The identifier of the advisory, as assigned by the issuing organization.
   */
  identifier: string;
  issuer: null | OrganizationSummary;
  /**
   * Informational labels attached by the system or users to this advisory.
   */
  labels: Labels;
  /**
   * The date (in RFC3339 format) of when the advisory was last modified, if any.
   */
  modified?: string | null;
  /**
   * The date (in RFC3339 format) of when the advisory was published, if any.
   */
  published: string | null;
  /**
   * The title of the advisory as assigned by the issuing organization.
   */
  title: string | null;
  /**
   * The opaque UUID of the advisory.
   */
  uuid: string;
  /**
   * The date (in RFC3339 format) of when the advisory was withdrawn, if any.
   */
  withdrawn: string | null;
};

export type AdvisorySummary = AdvisoryHead &
  (null | SourceDocument) & {
    /**
     * Average (arithmetic mean) score of the advisory aggregated from *all* related vulnerability assertions.
     */
    average_score: number | null;
    /**
     * Average (arithmetic mean) severity of the advisory aggregated from *all* related vulnerability assertions.
     */
    average_severity: string | null;
    /**
     * Vulnerabilities addressed within this advisory.
     */
    vulnerabilities: Array<AdvisoryVulnerabilityHead>;
  };

export type AdvisoryVulnerabilityHead = VulnerabilityHead & {
  /**
   * The average (arithmetic mean) score this advisory assigns to
   * the particular vulnerability.
   */
  score: number;
  /**
   * The English-language word description of the severity of the given
   * vulnerability, as asserted by the advisory, using the CVSS bucketing
   * ranges.
   *
   * Critical: 9.0–10.0
   * High: 7.0–8.9
   * Medium: 4.0–6.9
   * Low: 0.1–3.9
   * None: 0
   */
  severity: Severity;
};

/**
 * Summary of information from this advisory regarding a single specific vulnerability.
 */
export type AdvisoryVulnerabilitySummary = AdvisoryVulnerabilityHead & {
  /**
   * All CVSS3 scores from the advisory for the given vulnerability.
   * May include several, varying by minor version of the CVSS3 vector.
   */
  cvss3_scores: Array<string>;
};

export type AiFlags = {
  completions: boolean;
};

export type AiTool = {
  description: string;
  name: string;
  parameters: unknown;
};

export type AnalysisStatus = {
  /**
   * The number of graphs loaded in memory
   */
  graph_count: number;
  /**
   * The number of SBOMs found in the database
   */
  sbom_count: number;
};

export type AncNode = {
  cpe: Array<Cpe>;
  name: string;
  node_id: string;
  purl: Array<Purl>;
  relationship: string;
  sbom_id: string;
  version: string;
};

export type AncestorSummary = {
  ancestors: Array<AncNode>;
  cpe: Array<Cpe>;
  document_id: string;
  name: string;
  node_id: string;
  product_name: string;
  product_version: string;
  published: string;
  purl: Array<Purl>;
  sbom_id: string;
  version: string;
};

export type BasePurlDetails = BasePurlHead & {
  versions: Array<VersionedPurlSummary>;
};

export type BasePurlHead = {
  /**
   * The actual base PURL
   */
  purl: Purl;
  /**
   * The ID of the base PURL
   */
  uuid: string;
};

export type BasePurlSummary = BasePurlHead;

export type BinaryByteSize = string;

export type ChatMessage = {
  content: string;
  message_type: MessageType;
  timestamp: string;
};

export type ChatState = {
  internal_state?: string | null;
  messages: Array<ChatMessage>;
};

export type ClearlyDefinedCurationImporter = CommonImporter & {
  source?: string;
  types?: Array<ClearlyDefinedPackageType>;
};

export type ClearlyDefinedImporter = CommonImporter & {
  source?: string;
  types?: Array<ClearlyDefinedPackageType>;
};

export type ClearlyDefinedPackageType =
  | "composer"
  | "crate"
  | "deb"
  | "gem"
  | "git"
  | "go"
  | "maven"
  | "npm"
  | "nuget"
  | "pod"
  | "pypi";

export type CommonImporter = {
  /**
   * A description for users.
   */
  description?: string | null;
  /**
   * A flag to disable the importer, without deleting it.
   */
  disabled?: boolean;
  /**
   * Labels which will be applied to the ingested documents.
   */
  labels?: Labels;
  /**
   * The period the importer should be run.
   */
  period: string;
};

export type Conversation = {
  id: string;
  messages: Array<ChatMessage>;
  seq: number;
  updated_at: string;
};

export type ConversationSummary = {
  id: string;
  summary: string;
  updated_at: string;
};

export type Cpe = string;

export type CsafImporter = CommonImporter & {
  fetchRetries?: number | null;
  ignoreMissing?: boolean;
  onlyPatterns?: Array<string>;
  source: string;
  v3Signatures?: boolean;
};

export type CveImporter = CommonImporter & {
  source?: string;
  startYear?: number | null;
  years?: Array<number>;
};

export type CweImporter = CommonImporter & {
  source?: string;
};

export type DepNode = {
  cpe: Array<Cpe>;
  deps: Array<DepNode>;
  name: string;
  node_id: string;
  purl: Array<Purl>;
  relationship: string;
  sbom_id: string;
  version: string;
};

export type DepSummary = {
  cpe: Array<Cpe>;
  deps: Array<DepNode>;
  document_id: string;
  name: string;
  node_id: string;
  product_name: string;
  product_version: string;
  published: string;
  purl: Array<Purl>;
  sbom_id: string;
  version: string;
};

export type ExternalReferenceQuery = {
  cpe?: null | Cpe;
  purl?: null | Purl;
};

/**
 * A hash/digest prefixed with its type.
 */
export type Id = string;

export type Importer = ImporterData & {
  name: string;
};

export type ImporterConfiguration =
  | {
      sbom: SbomImporter;
    }
  | {
      csaf: CsafImporter;
    }
  | {
      osv: OsvImporter;
    }
  | {
      cve: CveImporter;
    }
  | {
      clearlyDefined: ClearlyDefinedImporter;
    }
  | {
      clearlyDefinedCuration: ClearlyDefinedCurationImporter;
    }
  | {
      cwe: CweImporter;
    };

export type ImporterData = {
  configuration: ImporterConfiguration;
  /**
   * The continuation token of the importer.
   */
  continuation?: unknown;
  /**
   * The last state change
   */
  lastChange: string;
  /**
   * The error of the last run (empty if successful)
   */
  lastError?: string | null;
  /**
   * The last run (successful or not)
   */
  lastRun?: string | null;
  /**
   * The last successful run
   */
  lastSuccess?: string | null;
  /**
   * The current progress.
   */
  progress?: Progress;
  /**
   * The current state of the importer
   */
  state: State;
};

export type ImporterReport = {
  /**
   * The time the report was created
   */
  creation: string;
  /**
   * Errors captured by the report
   */
  error?: string | null;
  /**
   * The ID of the report
   */
  id: string;
  /**
   * The name of the importer this report belongs to
   */
  importer: string;
  report?: null | Report;
};

/**
 * The result of the ingestion process
 */
export type IngestResult = {
  /**
   * The ID declared by the document
   */
  document_id?: string | null;
  /**
   * The internal ID of the document
   */
  id: Id;
  /**
   * Warnings that occurred during the import process
   */
  warnings?: Array<string>;
};

export type Labels = {
  [key: string]: string;
};

export type LicenseSummary = {
  id: string;
  license: string;
  purls: number;
  spdx_license_exceptions: Array<string>;
  spdx_licenses: Array<string>;
};

export type Message = {
  /**
   * The message
   */
  message: string;
  /**
   * The severity of the message
   */
  severity: Severity;
};

export type MessageType = "human" | "system" | "ai" | "tool";

export type OrganizationDetails = OrganizationHead & {
  /**
   * Advisories issued by the organization, if any.
   */
  advisories: Array<AdvisoryHead>;
};

/**
 * An organization who may issue advisories, product SBOMs, or
 * otherwise be involved in supply-chain evidence.
 */
export type OrganizationHead = {
  /**
   * The `CPE` key of the organization, if known.
   */
  cpe_key: string | null;
  /**
   * The opaque UUID of the organization.
   */
  id: string;
  /**
   * The name of the organization.
   */
  name: string;
  /**
   * The website of the organization, if known.
   */
  website: string | null;
};

export type OrganizationSummary = OrganizationHead;

export type OsvImporter = CommonImporter & {
  /**
   * An optional branch. Will use the default branch otherwise.
   */
  branch?: string | null;
  /**
   * An optional path to start searching for documents. Will use the root of the repository otherwise.
   */
  path?: string | null;
  /**
   * The URL to the git repository of the OSV data
   */
  source: string;
  startYear?: number | null;
  years?: Array<number>;
};

export type PaginatedResults_AdvisorySummary = {
  items: Array<
    AdvisoryHead &
      (null | SourceDocument) & {
        /**
         * Average (arithmetic mean) score of the advisory aggregated from *all* related vulnerability assertions.
         */
        average_score: number | null;
        /**
         * Average (arithmetic mean) severity of the advisory aggregated from *all* related vulnerability assertions.
         */
        average_severity: string | null;
        /**
         * Vulnerabilities addressed within this advisory.
         */
        vulnerabilities: Array<AdvisoryVulnerabilityHead>;
      }
  >;
  total: number;
};

export type PaginatedResults_BasePurlSummary = {
  items: Array<BasePurlHead>;
  total: number;
};

export type PaginatedResults_ConversationSummary = {
  items: Array<{
    id: string;
    summary: string;
    updated_at: string;
  }>;
  total: number;
};

export type PaginatedResults_ImporterReport = {
  items: Array<{
    /**
     * The time the report was created
     */
    creation: string;
    /**
     * Errors captured by the report
     */
    error?: string | null;
    /**
     * The ID of the report
     */
    id: string;
    /**
     * The name of the importer this report belongs to
     */
    importer: string;
    report?: null | Report;
  }>;
  total: number;
};

export type PaginatedResults_LicenseSummary = {
  items: Array<{
    id: string;
    license: string;
    purls: number;
    spdx_license_exceptions: Array<string>;
    spdx_licenses: Array<string>;
  }>;
  total: number;
};

export type PaginatedResults_ProductSummary = {
  items: Array<
    ProductHead & {
      vendor: null | OrganizationSummary;
      versions: Array<ProductVersionHead>;
    }
  >;
  total: number;
};

export type PaginatedResults_PurlSummary = {
  items: Array<
    PurlHead & {
      base: BasePurlHead;
      qualifiers: {
        [key: string]: string;
      };
      version: VersionedPurlHead;
    }
  >;
  total: number;
};

export type PaginatedResults_SbomPackage = {
  items: Array<{
    cpe: Array<string>;
    id: string;
    name: string;
    purl: Array<PurlSummary>;
    version?: string | null;
  }>;
  total: number;
};

export type PaginatedResults_SbomPackageRelation = {
  items: Array<{
    package: SbomPackage;
    relationship: Relationship;
  }>;
  total: number;
};

export type PaginatedResults_SbomSummary = {
  items: Array<
    SbomHead &
      (null | SourceDocument) & {
        described_by: Array<SbomPackage>;
      }
  >;
  total: number;
};

export type PaginatedResults_SpdxLicenseSummary = {
  items: Array<{
    id: string;
    name: string;
  }>;
  total: number;
};

export type PaginatedResults_VulnerabilitySummary = {
  items: Array<
    VulnerabilityHead & {
      advisories: Array<VulnerabilityAdvisoryHead>;
      /**
       * Average (arithmetic mean) score of the vulnerability aggregated from *all* related advisories.
       */
      average_score: number | null;
      average_severity: null | Severity;
    }
  >;
  total: number;
};

export type ProductDetails = ProductHead & {
  vendor: null | OrganizationSummary;
  versions: Array<ProductVersionDetails>;
};

export type ProductHead = {
  id: string;
  name: string;
};

export type ProductSbomHead = {
  labels: Labels;
  published: string | null;
};

export type ProductSummary = ProductHead & {
  vendor: null | OrganizationSummary;
  versions: Array<ProductVersionHead>;
};

export type ProductVersionDetails = ProductVersionHead & {
  sbom?: null | ProductSbomHead;
};

export type ProductVersionHead = {
  id: string;
  sbom_id?: string;
  version: string;
};

export type Progress = (null | ProgressDetails) & {
  message?: string | null;
};

export type ProgressDetails = {
  /**
   * The current processed items.
   */
  current: number;
  /**
   * The estimated time of completion.
   */
  estimatedCompletion: string;
  /**
   * The estimated remaining time in seconds.
   */
  estimatedSecondsRemaining: number;
  /**
   * Progress in percent (0..=1)
   */
  percent: number;
  /**
   * The average processing rate (per second).
   */
  rate: number;
  /**
   * The total number of items to be processed.
   */
  total: number;
};

export type Purl = string;

export type PurlAdvisory = AdvisoryHead & {
  status: Array<PurlStatus>;
};

export type PurlDetails = PurlHead & {
  advisories: Array<PurlAdvisory>;
  base: BasePurlHead;
  licenses: Array<PurlLicenseSummary>;
  relationships: {
    [key: string]: Array<string>;
  };
  version: VersionedPurlHead;
};

export type PurlHead = {
  /**
   * The actual qualified PURL
   */
  purl: Purl;
  /**
   * The ID of the qualified PURL
   */
  uuid: string;
};

export type PurlLicenseSummary = {
  licenses: Array<string>;
  sbom: SbomHead;
};

export type PurlStatus = {
  average_severity: Severity;
  context: null | StatusContext;
  status: string;
  vulnerability: VulnerabilityHead;
};

export type PurlSummary = PurlHead & {
  base: BasePurlHead;
  qualifiers: {
    [key: string]: string;
  };
  version: VersionedPurlHead;
};

export type Relationship =
  | "contained_by"
  | "dependency_of"
  | "dev_dependency_of"
  | "optional_dependency_of"
  | "provided_dependency_of"
  | "test_dependency_of"
  | "runtime_dependency_of"
  | "example_of"
  | "generated_from"
  | "ancestor_of"
  | "variant_of"
  | "build_tool_of"
  | "dev_tool_of"
  | "described_by"
  | "package_of"
  | "undefined";

export type Report = {
  /**
   * End of the import run
   */
  endDate: string;
  /**
   * Messages emitted during processing
   */
  messages?: {
    [key: string]: {
      [key: string]: Array<Message>;
    };
  };
  /**
   * Number of processes items
   */
  numberOfItems?: number;
  /**
   * Start of the import run
   */
  startDate: string;
};

/**
 * A struct wrapping an item with a revision.
 *
 * If the revision should not be part of the payload, but e.g. an HTTP header (like `ETag`), this
 * struct can help carrying both pieces.
 */
export type Revisioned_Importer = {
  /**
   * The revision.
   *
   * An opaque string that should have no meaning to the user, only to the backend.
   */
  revision: string;
  value: ImporterData & {
    name: string;
  };
};

export type SbomAdvisory = AdvisoryHead & {
  status: Array<SbomStatus>;
};

export type SbomHead = {
  authors: Array<string>;
  data_licenses: Array<string>;
  document_id?: string | null;
  id: string;
  labels: Labels;
  name: string;
  /**
   * The number of packages this SBOM has
   */
  number_of_packages: number;
  published: string | null;
};

export type SbomImporter = CommonImporter & {
  fetchRetries?: number | null;
  ignoreMissing?: boolean;
  keys?: Array<string>;
  onlyPatterns?: Array<string>;
  sizeLimit?: null | BinaryByteSize;
  source: string;
  v3Signatures?: boolean;
};

export type SbomPackage = {
  cpe: Array<string>;
  id: string;
  name: string;
  purl: Array<PurlSummary>;
  version?: string | null;
};

export type SbomPackageRelation = {
  package: SbomPackage;
  relationship: Relationship;
};

export type SbomStatus = VulnerabilityHead & {
  average_severity: Severity;
  context?: null | StatusContext;
  packages: Array<SbomPackage>;
  status: string;
};

export type SbomSummary = SbomHead &
  (null | SourceDocument) & {
    described_by: Array<SbomPackage>;
  };

/**
 * Qualitative Severity Rating Scale
 *
 * Described in CVSS v3.1 Specification: Section 5:
 * <https://www.first.org/cvss/specification-document#t17>
 *
 * > For some purposes it is useful to have a textual representation of the
 * > numeric Base, Temporal and Environmental scores.
 */
export type Severity = "none" | "low" | "medium" | "high" | "critical";

export type SourceDocument = {
  /**
   * The timestamp the document was ingested
   */
  ingested: string;
  sha256: string;
  sha384: string;
  sha512: string;
  size: number;
};

export type SpdxLicenseDetails = SpdxLicenseSummary & {
  text: string;
};

export type SpdxLicenseSummary = {
  id: string;
  name: string;
};

export type State = "waiting" | "running";

export type StatusContext =
  | {
      purl: Purl;
    }
  | {
      cpe: string;
    };

export type TypeCounts = {
  base: number;
  package: number;
  version: number;
};

export type TypeHead = {
  name: string;
};

export type TypeSummary = TypeHead & {
  counts: TypeCounts;
};

export type VersionedPurlAdvisory = AdvisoryHead & {
  status: Array<VersionedPurlStatus>;
};

export type VersionedPurlDetails = VersionedPurlHead & {
  advisories: Array<VersionedPurlAdvisory>;
  base: BasePurlHead;
  purls: Array<PurlHead>;
};

export type VersionedPurlHead = {
  /**
   * The actual, versioned PURL
   */
  purl: Purl;
  /**
   * The ID of the versioned PURL
   */
  uuid: string;
  /**
   * The version from the PURL
   */
  version: string;
};

export type VersionedPurlStatus = {
  status: string;
  vulnerability: VulnerabilityHead;
};

export type VersionedPurlSummary = VersionedPurlHead & {
  base: BasePurlHead;
  purls: Array<PurlHead>;
};

export type VulnerabilityAdvisoryHead = AdvisoryHead & {
  score: number | null;
  severity: null | Severity;
};

export type VulnerabilityAdvisoryStatus = {
  base_purl: BasePurlHead;
  context: null | StatusContext;
  version: string;
};

export type VulnerabilityAdvisorySummary = VulnerabilityAdvisoryHead & {
  /**
   * CVSS3 scores from this advisory regarding the vulnerability.
   */
  cvss3_scores: Array<string>;
  /**
   * The total number of vulnerabilities described by this advisory
   */
  number_of_vulnerabilities: number;
  purls: {
    [key: string]: Array<VulnerabilityAdvisoryStatus>;
  };
  /**
   * SBOMs claimed by this advisory to be addressed by this vulnerability.
   */
  sboms: Array<VulnerabilitySbomStatus>;
};

export type VulnerabilityDetails = VulnerabilityHead & {
  /**
   * Advisories addressing this vulnerability, if any.
   */
  advisories: Array<VulnerabilityAdvisorySummary>;
  /**
   * Average (arithmetic mean) score of the vulnerability aggregated from *all* related advisories.
   */
  average_score: number | null;
  average_severity: null | Severity;
};

export type VulnerabilityHead = {
  /**
   * Associated CWE, if any.
   */
  cwes: Array<string>;
  /**
   * The description of the vulnerability, if known.
   */
  description: string | null;
  /**
   * The date (in RFC3339 format) of when the vulnerability was discovered, if any.
   */
  discovered: string | null;
  /**
   * The globally-unique identifier for the vulnerability.
   * Traditionally (but not required) refers to the assigned
   * CVE identifier.
   */
  identifier: string;
  /**
   * The date (in RFC3339 format) of when the vulnerability was last modified, if any.
   */
  modified: string | null;
  normative: boolean;
  /**
   * The date (in RFC3339 format) of when the vulnerability was published, if any.
   */
  published: string | null;
  /**
   * The date (in RFC3339 format) of when software containing the vulnerability first released, if known.
   */
  released: string | null;
  /**
   * The date (in RFC3339 format) of when the vulnerability identifier was reserved, if any.
   */
  reserved: string | null;
  /**
   * The title of the vulnerability, if known.
   */
  title: string | null;
  /**
   * The date (in RFC3339 format) of when the vulnerability was last withdrawn, if any.
   */
  withdrawn: string | null;
};

export type VulnerabilitySbomStatus = SbomHead & {
  purl_statuses: {
    [key: string]: Array<PurlSummary>;
  };
  version?: string | null;
};

export type VulnerabilitySummary = VulnerabilityHead & {
  advisories: Array<VulnerabilityAdvisoryHead>;
  /**
   * Average (arithmetic mean) score of the vulnerability aggregated from *all* related advisories.
   */
  average_score: number | null;
  average_severity: null | Severity;
};

export type InfoResponse = {
  build?: {
    [key: string]: unknown;
  };
  version: string;
};

export type InfoError = unknown;

export type ListAdvisoriesData = {
  query?: {
    deprecated?: "Ignore" | "Consider";
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListAdvisoriesResponse = PaginatedResults_AdvisorySummary;

export type ListAdvisoriesError = unknown;

export type UploadAdvisoryData = {
  body: Blob | File;
  query: {
    /**
     * Optional issuer if it cannot be determined from advisory contents.
     */
    issuer?: string | null;
    /**
     * Optional labels.
     *
     * Only use keys with a prefix of `labels.`
     */
    labels: Labels;
  };
};

export type UploadAdvisoryResponse = unknown;

export type UploadAdvisoryError = unknown;

export type UpdateAdvisoryLabelsData = {
  body: Labels;
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: Id;
  };
};

export type UpdateAdvisoryLabelsResponse = void;

export type UpdateAdvisoryLabelsError = unknown;

export type PatchAdvisoryLabelsData = {
  body: Labels;
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: Id;
  };
};

export type PatchAdvisoryLabelsResponse = void;

export type PatchAdvisoryLabelsError = unknown;

export type GetAdvisoryData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    key: string;
  };
};

export type GetAdvisoryResponse = AdvisoryDetails;

export type GetAdvisoryError = unknown;

export type DeleteAdvisoryData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    key: string;
  };
};

export type DeleteAdvisoryResponse = AdvisoryDetails;

export type DeleteAdvisoryError = unknown;

export type DownloadAdvisoryData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>'
     */
    key: string;
  };
};

export type DownloadAdvisoryResponse = Blob | File;

export type DownloadAdvisoryError = unknown;

export type CompletionsData = {
  body: ChatState;
};

export type CompletionsResponse = ChatState;

export type CompletionsError = unknown;

export type ListConversationsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListConversationsResponse = PaginatedResults_ConversationSummary;

export type ListConversationsError = unknown;

export type CreateConversationResponse = Conversation;

export type CreateConversationError = unknown;

export type GetConversationData = {
  path: {
    /**
     * Opaque ID of the conversation
     */
    id: string;
  };
};

export type GetConversationResponse = Conversation;

export type GetConversationError = unknown;

export type UpdateConversationData = {
  body: Array<ChatMessage>;
  headers?: {
    /**
     * The revision to update
     */
    "if-match"?: string | null;
  };
  path: {
    /**
     * Opaque ID of the conversation
     */
    id: string;
  };
};

export type UpdateConversationResponse = Conversation;

export type UpdateConversationError = unknown;

export type DeleteConversationData = {
  path: {
    /**
     * Opaque ID of the conversation
     */
    id: string;
  };
};

export type DeleteConversationResponse = Conversation;

export type DeleteConversationError = unknown;

export type AiFlagsResponse = AiFlags;

export type AiFlagsError = unknown;

export type AiToolsResponse = Array<AiTool>;

export type AiToolsError = unknown;

export type AiToolCallData = {
  body: unknown;
  path: {
    /**
     * Name of the tool to call
     */
    name: string;
  };
};

export type AiToolCallResponse = string;

export type AiToolCallError = unknown;

export type SearchComponentDepsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type SearchComponentDepsResponse = DepSummary;

export type SearchComponentDepsError = unknown;

export type GetComponentDepsData = {
  path: {
    /**
     * provide component name or URL-encoded pURL itself
     */
    key: string;
  };
};

export type GetComponentDepsResponse = DepSummary;

export type GetComponentDepsError = unknown;

export type SearchComponentRootComponentsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type SearchComponentRootComponentsResponse = AncestorSummary;

export type SearchComponentRootComponentsError = unknown;

export type GetComponentRootComponentsData = {
  path: {
    /**
     * provide component name or URL-encoded pURL itself
     */
    key: string;
  };
};

export type GetComponentRootComponentsResponse = AncestorSummary;

export type GetComponentRootComponentsError = unknown;

export type StatusResponse = AnalysisStatus;

export type StatusError = unknown;

export type UploadDatasetData = {
  body: Blob | File;
  query: {
    /**
     * Optional labels.
     *
     * Only use keys with a prefix of `labels.`
     */
    labels: Labels;
  };
};

export type UploadDatasetResponse = unknown;

export type UploadDatasetError = unknown;

export type ListImportersResponse = Array<Importer>;

export type ListImportersError = unknown;

export type GetImporterData = {
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type GetImporterResponse = Revisioned_Importer;

export type GetImporterError = unknown;

export type UpdateImporterData = {
  body: ImporterConfiguration;
  headers?: {
    /**
     * The revision to update
     */
    "if-match"?: string | null;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type UpdateImporterResponse = unknown;

export type UpdateImporterError = unknown;

export type CreateImporterData = {
  body: ImporterConfiguration;
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type CreateImporterResponse = unknown;

export type CreateImporterError = unknown;

export type DeleteImporterData = {
  headers?: {
    /**
     * The revision to delete
     */
    "if-match"?: string | null;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type DeleteImporterResponse = unknown;

export type DeleteImporterError = unknown;

export type PatchImporterData = {
  body: unknown;
  headers?: {
    /**
     * The revision to update
     */
    "if-match"?: string | null;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type PatchImporterResponse = unknown;

export type PatchImporterError = unknown;

export type EnableImporterData = {
  body: boolean;
  headers?: {
    /**
     * The revision to update
     */
    "if-match"?: string | null;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type EnableImporterResponse = unknown;

export type EnableImporterError = unknown;

export type ForceRunImporterData = {
  body: boolean;
  headers?: {
    /**
     * The revision to update
     */
    "if-match"?: string | null;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type ForceRunImporterResponse = unknown;

export type ForceRunImporterError = unknown;

export type ListImporterReportsData = {
  path: {
    name: string;
  };
};

export type ListImporterReportsResponse = PaginatedResults_ImporterReport;

export type ListImporterReportsError = unknown;

export type ListLicensesData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListLicensesResponse = PaginatedResults_LicenseSummary;

export type ListLicensesError = unknown;

export type ListSpdxLicensesData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListSpdxLicensesResponse = PaginatedResults_SpdxLicenseSummary;

export type ListSpdxLicensesError = unknown;

export type GetSpdxLicenseData = {
  path: {
    id: string;
  };
};

export type GetSpdxLicenseResponse = SpdxLicenseDetails;

export type GetSpdxLicenseError = unknown;

export type GetLicensesData = {
  path: {
    uuid: string;
  };
};

export type GetLicensesResponse = LicenseSummary;

export type GetLicensesError = unknown;

export type GetLicensePurlsData = {
  path: {
    uuid: string;
  };
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type GetLicensePurlsResponse = LicenseSummary;

export type GetLicensePurlsError = unknown;

export type ListOrganizationsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListOrganizationsResponse = OrganizationSummary;

export type ListOrganizationsError = unknown;

export type GetOrganizationData = {
  path: {
    /**
     * Opaque ID of the organization
     */
    id: string;
  };
};

export type GetOrganizationResponse = OrganizationDetails;

export type GetOrganizationError = unknown;

export type ListProductsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListProductsResponse = PaginatedResults_ProductSummary;

export type ListProductsError = unknown;

export type GetProductData = {
  path: {
    /**
     * Opaque ID of the product
     */
    id: string;
  };
};

export type GetProductResponse = ProductDetails;

export type GetProductError = unknown;

export type DeleteProductData = {
  path: {
    /**
     * Opaque ID of the product
     */
    id: string;
  };
};

export type DeleteProductResponse = ProductDetails;

export type DeleteProductError = unknown;

export type ListPurlData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListPurlResponse = PaginatedResults_PurlSummary;

export type ListPurlError = unknown;

export type ListBasePurlsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListBasePurlsResponse = PaginatedResults_BasePurlSummary;

export type ListBasePurlsError = unknown;

export type GetBasePurlData = {
  path: {
    /**
     * opaque identifier for a base PURL, or a URL-encoded pURL itself
     */
    key: string;
  };
};

export type GetBasePurlResponse = BasePurlDetails;

export type GetBasePurlError = unknown;

export type ListPurlTypesResponse = Array<TypeSummary>;

export type ListPurlTypesError = unknown;

export type GetPurlTypeData = {
  path: {
    /**
     * PURL identifier of a type
     */
    type: string;
  };
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type GetPurlTypeResponse = PaginatedResults_BasePurlSummary;

export type GetPurlTypeError = unknown;

export type GetBasePurlOfTypeData = {
  path: {
    /**
     * name of the package optionally preceded by its namespace
     */
    namespace_and_name: string;
    /**
     * PURL identifier of a type
     */
    type: string;
  };
};

export type GetBasePurlOfTypeResponse = BasePurlDetails;

export type GetBasePurlOfTypeError = unknown;

export type GetVersionedPurlOfTypeData = {
  path: {
    /**
     * name of the package optionally preceded by its namespace
     */
    namespace_and_name: string;
    /**
     * PURL identifier of a type
     */
    type: string;
    /**
     * version of the package
     */
    version: string;
  };
};

export type GetVersionedPurlOfTypeResponse = VersionedPurlDetails;

export type GetVersionedPurlOfTypeError = unknown;

export type GetVersionedPurlData = {
  path: {
    /**
     * opaque ID identifier for a package version, or URL-ecnoded pURL itself
     */
    key: string;
  };
};

export type GetVersionedPurlResponse = VersionedPurlDetails;

export type GetVersionedPurlError = unknown;

export type GetPurlData = {
  path: {
    /**
     * opaque identifier for a fully-qualified PURL, or URL-encoded pURL itself
     */
    key: string;
  };
  query?: {
    deprecated?: "Ignore" | "Consider";
  };
};

export type GetPurlResponse = PurlDetails;

export type GetPurlError = unknown;

export type ListSbomsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListSbomsResponse = PaginatedResults_SbomSummary;

export type ListSbomsError = unknown;

export type UploadSbomData = {
  body: Array<number>;
  query: {
    /**
     * Optional labels.
     *
     * Only use keys with a prefix of `labels.`
     */
    labels: Labels;
    /**
     * Source the document came from
     */
    location: string;
  };
};

export type UploadSbomResponse = IngestResult;

export type UploadSbomError = unknown;

export type ListRelatedSbomsData = {
  query?: {
    /**
     * Find by CPE
     */
    cpe?: null | Cpe;
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    /**
     * Find by PURL
     */
    purl?: null | Purl;
    q?: string;
    sort?: string;
  };
};

export type ListRelatedSbomsResponse = PaginatedResults_SbomSummary;

export type ListRelatedSbomsError = unknown;

export type CountRelatedSbomsData = {
  body: Array<ExternalReferenceQuery>;
  path: {
    /**
     * Find by CPE
     */
    cpe: null | Cpe;
    /**
     * Find by PURL
     */
    purl: null | Purl;
  };
};

export type CountRelatedSbomsResponse = Array<number>;

export type CountRelatedSbomsError = unknown;

export type GetSbomData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: string;
  };
};

export type GetSbomResponse = SbomSummary;

export type GetSbomError = unknown;

export type DeleteSbomData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: string;
  };
};

export type DeleteSbomResponse = SbomSummary;

export type DeleteSbomError = unknown;

export type GetSbomAdvisoriesData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: string;
  };
};

export type GetSbomAdvisoriesResponse = Array<SbomAdvisory>;

export type GetSbomAdvisoriesError = unknown;

export type UpdateSbomLabelsData = {
  body: Labels;
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: Id;
  };
};

export type UpdateSbomLabelsResponse = void;

export type UpdateSbomLabelsError = unknown;

export type PatchSbomLabelsData = {
  body: Labels;
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: Id;
  };
};

export type PatchSbomLabelsResponse = void;

export type PatchSbomLabelsError = unknown;

export type ListPackagesData = {
  path: {
    /**
     * ID of the SBOM to get packages for
     */
    id: string;
  };
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListPackagesResponse = PaginatedResults_SbomPackage;

export type ListPackagesError = unknown;

export type ListRelatedPackagesData = {
  path: {
    /**
     * ID of SBOM to search packages in
     */
    id: string;
  };
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    /**
     * The Package to use as reference
     */
    reference?: string | null;
    /**
     * Optional relationship filter
     */
    relationship?: null | Relationship;
    sort?: string;
    /**
     * Which side the reference should be on
     */
    which?: "left" | "right";
  };
};

export type ListRelatedPackagesResponse = PaginatedResults_SbomPackageRelation;

export type ListRelatedPackagesError = unknown;

export type DownloadSbomData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>'
     */
    key: string;
  };
};

export type DownloadSbomResponse = Blob | File;

export type DownloadSbomError = unknown;

export type GetUserPreferencesData = {
  path: {
    /**
     * The key to the user preferences
     */
    key: string;
  };
};

export type GetUserPreferencesResponse = unknown;

export type GetUserPreferencesError = unknown;

export type SetUserPreferencesData = {
  body: unknown;
  headers?: {
    /**
     * The revision to update
     */
    "if-match"?: string | null;
  };
  path: {
    /**
     * The key to the user preferences
     */
    key: string;
  };
};

export type SetUserPreferencesResponse = string;

export type SetUserPreferencesError = unknown;

export type DeleteUserPreferencesData = {
  body: unknown;
  headers?: {
    /**
     * The revision to delete
     */
    "if-match"?: string | null;
  };
  path: {
    /**
     * The key to the user preferences
     */
    key: string;
  };
};

export type DeleteUserPreferencesResponse = unknown;

export type DeleteUserPreferencesError = unknown;

export type ListVulnerabilitiesData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListVulnerabilitiesResponse = PaginatedResults_VulnerabilitySummary;

export type ListVulnerabilitiesError = unknown;

export type GetVulnerabilityData = {
  path: {
    /**
     * ID of the vulnerability
     */
    id: string;
  };
};

export type GetVulnerabilityResponse = VulnerabilityDetails;

export type GetVulnerabilityError = unknown;

export type DeleteVulnerabilityData = {
  path: {
    /**
     * ID of the vulnerability
     */
    id: string;
  };
};

export type DeleteVulnerabilityResponse = VulnerabilityDetails;

export type DeleteVulnerabilityError = unknown;

export type ListWeaknessesData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListWeaknessesResponse = PaginatedResults_LicenseSummary;

export type ListWeaknessesError = unknown;

export type GetWeaknessData = {
  path: {
    id: string;
  };
};

export type GetWeaknessResponse = LicenseSummary;

export type GetWeaknessError = unknown;
