// This file is auto-generated by @hey-api/openapi-ts

export type AdvisoryDetails = AdvisoryHead & {
  /**
   * Average (arithmetic mean) score of the advisory aggregated from *all* related vulnerability assertions.
   */
  average_score: number | null;
  average_severity: Severity | null;
  /**
   * Vulnerabilities addressed within this advisory.
   */
  vulnerabilities: Array<AdvisoryVulnerabilitySummary>;
};

export type AdvisoryHead = {
  /**
   * Hashes of the underlying original document as ingested.
   */
  hashes: Array<Id>;
  /**
   * The identifier of the advisory, as assigned by the issuing organization.
   */
  identifier: string;
  issuer: OrganizationSummary | null;
  labels: Labels;
  /**
   * The date (in RFC3339 format) of when the advisory was last modified, if any.
   */
  modified?: string | null;
  /**
   * The date (in RFC3339 format) of when the advisory was published, if any.
   */
  published: string | null;
  /**
   * The title of the advisory as assigned by the issuing organization.
   */
  title: string | null;
  /**
   * The opaque UUID of the advisory.
   */
  uuid: string;
  /**
   * The date (in RFC3339 format) of when the advisory was withdrawn, if any.
   */
  withdrawn: string | null;
};

export type AdvisorySummary = AdvisoryHead & {
  /**
   * Average (arithmetic mean) score of the advisory aggregated from *all* related vulnerability assertions.
   */
  average_score: number | null;
  /**
   * Average (arithmetic mean) severity of the advisory aggregated from *all* related vulnerability assertions.
   */
  average_severity: string | null;
  /**
   * Vulnerabilities addressed within this advisory.
   */
  vulnerabilities: Array<AdvisoryVulnerabilityHead>;
};

export type AdvisoryVulnerabilityAssertions = {
  assertions: {
    [key: string]: Array<Assertion>;
  };
};

export type AdvisoryVulnerabilityHead = VulnerabilityHead & {
  /**
   * The average (arithmetic mean) score this advisory assigns to
   * the particular vulnerability.
   */
  score: number;
  severity: Severity;
};

/**
 * Summary of information from this advisory regarding a single specific vulnerability.
 */
export type AdvisoryVulnerabilitySummary = AdvisoryVulnerabilityHead & {
  /**
   * All CVSS3 scores from the advisory for the given vulnerability.
   * May include several, varying by minor version of the CVSS3 vector.
   */
  cvss3_scores: Array<string>;
};

export type Assertion =
  | {
      affected: {
        end_version: string;
        start_version: string;
      };
    }
  | {
      not_affected: {
        version: string;
      };
    }
  | {
      fixed: {
        version: string;
      };
    };

export type BasePurlDetails = BasePurlHead & {
  versions: Array<VersionedPurlSummary>;
};

export type BasePurlHead = {
  purl: Purl;
  /**
   * The ID of the base PURL
   */
  uuid: string;
};

export type BasePurlSummary = BasePurlHead & {
  [key: string]: unknown;
};

export type BinaryByteSize = string;

export type CommonImporter = {
  /**
   * A description for users.
   */
  description?: string | null;
  /**
   * A flag to disable the importer, without deleting it.
   */
  disabled?: boolean;
  labels?: Labels;
  /**
   * The period the importer should be run.
   */
  period: string;
};

export type CsafImporter = CommonImporter & {
  fetchRetries?: number | null;
  onlyPatterns?: Array<string>;
  source: string;
  v3Signatures?: boolean;
};

export type CveImporter = CommonImporter & {
  source?: string;
  startYear?: number | null;
  years?: Array<number>;
};

/**
 * A hash/digest prefixed with its type.
 */
export type Id = string;

export type Importer = ImporterData & {
  name: string;
};

export type ImporterConfiguration =
  | {
      sbom: SbomImporter;
    }
  | {
      csaf: CsafImporter;
    }
  | {
      osv: OsvImporter;
    }
  | {
      cve: CveImporter;
    };

export type ImporterData = {
  configuration: ImporterConfiguration;
  /**
   * The continuation token of the importer.
   */
  continuation?: unknown;
  /**
   * The last state change
   */
  lastChange: string;
  /**
   * The error of the last run (empty if successful)
   */
  lastError?: string | null;
  /**
   * The last run (successful or not)
   */
  lastRun?: string | null;
  /**
   * The last successful run
   */
  lastSuccess?: string | null;
  state: State;
};

export type ImporterReport = {
  creation: string;
  error?: string | null;
  id: string;
  importer: string;
  report: unknown;
};

export type Labels = {
  [key: string]: string;
};

export type OrganizationDetails = OrganizationHead & {
  /**
   * Advisories issued by the organization, if any.
   */
  advisories: Array<AdvisoryHead>;
};

/**
 * An organization who may issue advisories, product SBOMs, or
 * otherwise be involved in supply-chain evidence.
 */
export type OrganizationHead = {
  /**
   * The `CPE` key of the organization, if known.
   */
  cpe_key: string | null;
  /**
   * The opaque UUID of the organization.
   */
  id: string;
  /**
   * The name of the organization.
   */
  name: string;
  /**
   * The website of the organization, if known.
   */
  website: string | null;
};

export type OrganizationSummary = OrganizationHead & {
  [key: string]: unknown;
};

export type OsvImporter = CommonImporter & {
  /**
   * An optional branch. Will use the default branch otherwise.
   */
  branch?: string | null;
  /**
   * An optional path to start searching for documents. Will use the root of the repository otherwise.
   */
  path?: string | null;
  /**
   * The URL to the git repository of the OSV data
   */
  source: string;
};

/**
 * Paginated returned items
 */
export type PaginatedAdvisorySummary = {
  /**
   * Returned items
   */
  items: Array<AdvisorySummary>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedBasePurlSummary = {
  /**
   * Returned items
   */
  items: Array<BasePurlSummary>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedImporterReport = {
  /**
   * Returned items
   */
  items: Array<ImporterReport>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedOrganizationSummary = {
  /**
   * Returned items
   */
  items: Array<OrganizationSummary>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedProductSummary = {
  /**
   * Returned items
   */
  items: Array<ProductSummary>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedPurlSummary = {
  /**
   * Returned items
   */
  items: Array<PurlSummary>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedSbomPackage = {
  /**
   * Returned items
   */
  items: Array<SbomPackage>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedSbomPackageRelation = {
  /**
   * Returned items
   */
  items: Array<SbomPackageRelation>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedSbomSummary = {
  /**
   * Returned items
   */
  items: Array<SbomSummary>;
  /**
   * Total number of items found
   */
  total: number;
};

/**
 * Paginated returned items
 */
export type PaginatedVulnerabilitySummary = {
  /**
   * Returned items
   */
  items: Array<VulnerabilitySummary>;
  /**
   * Total number of items found
   */
  total: number;
};

export type ProductDetails = ProductHead & {
  vendor: OrganizationSummary | null;
  versions: Array<ProductVersionDetails>;
};

export type ProductHead = {
  id: string;
  name: string;
};

export type ProductSummary = ProductHead & {
  vendor: OrganizationSummary | null;
  versions: Array<ProductVersionHead>;
};

export type ProductVersionDetails = ProductVersionHead & {
  sbom?: SbomHead | null;
};

export type ProductVersionHead = {
  id: string;
  sbom_id?: string | null;
  version: string;
};

export type Purl = string;

export type PurlAdvisory = AdvisoryHead & {
  status: Array<PurlStatus>;
};

export type PurlDetails = PurlHead & {
  advisories: Array<PurlAdvisory>;
  base: BasePurlHead;
  version: VersionedPurlHead;
};

export type PurlHead = {
  purl: Purl;
  /**
   * The ID of the qualified PURL
   */
  uuid: string;
};

export type PurlStatus = {
  context: StatusContext | null;
  status: string;
  vulnerability: VulnerabilityHead;
};

export type PurlSummary = PurlHead & {
  base: BasePurlHead;
  qualifiers: {
    [key: string]: string;
  };
  version: VersionedPurlHead;
};

export type Relationship =
  | "contained_by"
  | "dependency_of"
  | "dev_dependency_of"
  | "optional_dependency_of"
  | "provided_dependency_of"
  | "test_dependency_of"
  | "runtime_dependency_of"
  | "example_of"
  | "generated_from"
  | "ancestor_of"
  | "variant_of"
  | "build_tool_of"
  | "dev_tool_of"
  | "described_by";

/**
 * A struct wrapping an item with a revision.
 *
 * If the revision should not be part of the payload, but e.g. an HTTP header (like `ETag`), this
 * struct can help carrying both pieces.
 */
export type RevisionedImporter = {
  /**
   * The revision.
   *
   * An opaque string that should have no meaning to the user, only to the backend.
   */
  revision: string;
  value: Importer;
};

export type SbomAdvisory = AdvisoryHead & {
  status: Array<SbomStatus>;
};

export type SbomDetails = SbomSummary & {
  advisories: Array<SbomAdvisory>;
};

export type SbomHead = {
  authors: Array<string>;
  document_id: string;
  hashes: Array<Id>;
  id: string;
  labels: Labels;
  name: string;
  published: string | null;
};

export type SbomImporter = CommonImporter & {
  fetchRetries?: number | null;
  keys?: Array<string>;
  onlyPatterns?: Array<string>;
  sizeLimit?: BinaryByteSize | null;
  source: string;
  v3Signatures?: boolean;
};

export type SbomPackage = {
  cpe: Array<string>;
  id: string;
  name: string;
  purl: Array<PurlSummary>;
  version?: string | null;
};

export type SbomPackageRelation = {
  package: SbomPackage;
  relationship: Relationship;
};

export type SbomStatus = {
  context?: StatusContext | null;
  packages: Array<SbomPackage>;
  status: string;
  vulnerability_id: string;
};

export type SbomSummary = SbomHead & {
  described_by: Array<SbomPackage>;
};

/**
 * Qualitative Severity Rating Scale
 *
 * Described in CVSS v3.1 Specification: Section 5:
 * <https://www.first.org/cvss/specification-document#t17>
 *
 * > For some purposes it is useful to have a textual representation of the
 * > numeric Base, Temporal and Environmental scores.
 */
export type Severity = "none" | "low" | "medium" | "high" | "critical";

export type State = "waiting" | "running";

export type StatusContext =
  | {
      purl: Purl;
    }
  | {
      cpe: string;
    };

export type TypeCounts = {
  base: number;
  package: number;
  version: number;
};

export type TypeHead = {
  name: string;
};

export type TypeSummary = TypeHead & {
  counts: TypeCounts;
};

/**
 * a UUID
 */
export type Uuid = string;

export type VersionedPurlAdvisory = AdvisoryHead & {
  status: Array<VersionedPurlStatus>;
};

export type VersionedPurlDetails = VersionedPurlHead & {
  advisories: Array<VersionedPurlAdvisory>;
  base: BasePurlHead;
  purls: Array<PurlHead>;
};

export type VersionedPurlHead = {
  purl: Purl;
  /**
   * The ID of the versioned PURL
   */
  uuid: string;
  /**
   * The version from the PURL
   */
  version: string;
};

export type VersionedPurlStatus = {
  status: string;
  vulnerability: VulnerabilityHead;
};

export type VersionedPurlSummary = VersionedPurlHead & {
  base: BasePurlHead;
  purls: Array<PurlHead>;
};

export type VulnerabilityAdvisoryHead = AdvisoryHead & {
  score: number | null;
  severity: Severity | null;
};

export type VulnerabilityAdvisoryStatus = {
  base_purl: BasePurlHead;
  context: StatusContext | null;
  version: string;
};

export type VulnerabilityAdvisorySummary = VulnerabilityAdvisoryHead & {
  /**
   * CVSS3 scores from this advisory regarding the vulnerability.
   */
  cvss3_scores: Array<string>;
  purls: {
    [key: string]: Array<VulnerabilityAdvisoryStatus>;
  };
  /**
   * SBOMs claimed by this advisory to be addressed by this vulnerability.
   */
  sboms: Array<VulnerabilitySbomStatus>;
};

export type VulnerabilityDetails = VulnerabilityHead & {
  /**
   * Advisories addressing this vulnerability, if any.
   */
  advisories: Array<VulnerabilityAdvisorySummary>;
  /**
   * Average (arithmetic mean) score of the vulnerability aggregated from *all* related advisories.
   */
  average_score: number | null;
  average_severity: Severity | null;
};

export type VulnerabilityHead = {
  /**
   * Associated CWE, if any.
   */
  cwe: string | null;
  /**
   * The description of the vulnerability, if known.
   */
  description: string | null;
  /**
   * The date (in RFC3339 format) of when the vulnerability was discovered, if any.
   */
  discovered: string | null;
  /**
   * The globally-unique identifier for the vulnerability.
   * Traditionally (but not required) refers to the assigned
   * CVE identifier.
   */
  identifier: string;
  /**
   * The date (in RFC3339 format) of when the vulnerability was last modified, if any.
   */
  modified: string | null;
  normative: boolean;
  /**
   * The date (in RFC3339 format) of when the vulnerability was published, if any.
   */
  published: string | null;
  /**
   * The date (in RFC3339 format) of when software containing the vulnerability first released, if known.
   */
  released: string | null;
  /**
   * The title of the vulnerability, if known.
   */
  title: string | null;
  /**
   * The date (in RFC3339 format) of when the vulnerability was last withdrawn, if any.
   */
  withdrawn: string | null;
};

export type VulnerabilitySbomStatus = SbomHead & {
  status: Array<string>;
  version?: string | null;
};

export type VulnerabilitySummary = VulnerabilityHead & {
  advisories: Array<VulnerabilityAdvisoryHead>;
  /**
   * Average (arithmetic mean) score of the vulnerability aggregated from *all* related advisories.
   */
  average_score: number | null;
  average_severity: Severity | null;
};

export type Which = "left" | "right";

export type ListAdvisoriesData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListAdvisoriesResponse = PaginatedAdvisorySummary;

export type ListAdvisoriesError = unknown;

export type UploadAdvisoryData = {
  body: Blob | File;
  query: {
    /**
     * Optional issuer if it cannot be determined from advisory contents.
     */
    issuer?: string | null;
    /**
     * Optional labels.
     *
     * Only use keys with a prefix of `labels.`
     */
    labels: Labels;
  };
};

export type UploadAdvisoryResponse = unknown;

export type UploadAdvisoryError = unknown;

export type UpdateAdvisoryLabelsData = {
  body: Labels;
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: Id;
  };
};

export type UpdateAdvisoryLabelsResponse = void;

export type UpdateAdvisoryLabelsError = unknown;

export type PatchAdvisoryLabelsData = {
  body: Labels;
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: Id;
  };
};

export type PatchAdvisoryLabelsResponse = void;

export type PatchAdvisoryLabelsError = unknown;

export type GetAdvisoryData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    key: string;
  };
};

export type GetAdvisoryResponse = AdvisoryDetails;

export type GetAdvisoryError = unknown;

export type DeleteAdvisoryData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    key: string;
  };
};

export type DeleteAdvisoryResponse = AdvisoryDetails;

export type DeleteAdvisoryError = unknown;

export type DownloadAdvisoryData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>'
     */
    key: string;
  };
};

export type DownloadAdvisoryResponse = Blob | File;

export type DownloadAdvisoryError = unknown;

export type ListImportersResponse = Array<Importer>;

export type ListImportersError = unknown;

export type GetImporterData = {
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type GetImporterResponse = RevisionedImporter;

export type GetImporterError = unknown;

export type CreateImporterData = {
  body: ImporterConfiguration;
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type CreateImporterResponse = unknown;

export type CreateImporterError = unknown;

export type UpdateImporterData = {
  body: ImporterConfiguration;
  headers: {
    /**
     * The revision to update
     */
    "if-match": string;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type UpdateImporterResponse = unknown;

export type UpdateImporterError = unknown;

export type DeleteImporterData = {
  headers: {
    /**
     * The revision to delete
     */
    "if-match": string;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type DeleteImporterResponse = unknown;

export type DeleteImporterError = unknown;

export type EnableImporterData = {
  body: boolean;
  headers: {
    /**
     * The revision to update
     */
    "if-match": string;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type EnableImporterResponse = unknown;

export type EnableImporterError = unknown;

export type ForceRunImporterData = {
  body: boolean;
  headers: {
    /**
     * The revision to update
     */
    "if-match": string;
  };
  path: {
    /**
     * The name of the importer
     */
    name: string;
  };
};

export type ForceRunImporterResponse = unknown;

export type ForceRunImporterError = unknown;

export type GetImporterReportsData = {
  path: {
    name: string;
  };
};

export type GetImporterReportsResponse = PaginatedImporterReport;

export type GetImporterReportsError = unknown;

export type ListOrganizationsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListOrganizationsResponse = PaginatedOrganizationSummary;

export type ListOrganizationsError = unknown;

export type GetOrganizationData = {
  path: {
    /**
     * Opaque ID of the organization
     */
    id: string;
  };
};

export type GetOrganizationResponse = OrganizationDetails;

export type GetOrganizationError = unknown;

export type ListProductsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListProductsResponse = PaginatedProductSummary;

export type ListProductsError = unknown;

export type GetProductData = {
  path: {
    /**
     * Opaque ID of the product
     */
    id: string;
  };
};

export type GetProductResponse = ProductDetails;

export type GetProductError = unknown;

export type DeleteProductData = {
  path: {
    /**
     * Opaque ID of the product
     */
    id: string;
  };
};

export type DeleteProductResponse = ProductDetails;

export type DeleteProductError = unknown;

export type ListPurlData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListPurlResponse = PaginatedPurlSummary;

export type ListPurlError = unknown;

export type ListBasePurlsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListBasePurlsResponse = PaginatedBasePurlSummary;

export type ListBasePurlsError = unknown;

export type GetBasePurlData = {
  path: {
    /**
     * opaque identifier for a base PURL, or a URL-encoded pURL itself
     */
    key: string;
  };
};

export type GetBasePurlResponse = BasePurlDetails;

export type GetBasePurlError = unknown;

export type ListPurlTypesResponse = Array<TypeSummary>;

export type ListPurlTypesError = unknown;

export type GetPurlTypeData = {
  path: {
    /**
     * PURL identifier of a type
     */
    type: string;
  };
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type GetPurlTypeResponse = PaginatedBasePurlSummary;

export type GetPurlTypeError = unknown;

export type GetBasePurlOfTypeData = {
  path: {
    /**
     * name of the package optionally preceded by its namespace
     */
    namespace_and_name: string;
    /**
     * PURL identifier of a type
     */
    type: string;
  };
};

export type GetBasePurlOfTypeResponse = BasePurlDetails;

export type GetBasePurlOfTypeError = unknown;

export type GetVersionedPurlOfTypeData = {
  path: {
    /**
     * name of the package optionally preceded by its namespace
     */
    namespace_and_name: string;
    /**
     * PURL identifier of a type
     */
    type: string;
    /**
     * version of the package
     */
    version: string;
  };
};

export type GetVersionedPurlOfTypeResponse = VersionedPurlDetails;

export type GetVersionedPurlOfTypeError = unknown;

export type GetVersionedPurlData = {
  path: {
    /**
     * opaque ID identifier for a package version, or URL-ecnoded pURL itself
     */
    key: string;
  };
};

export type GetVersionedPurlResponse = VersionedPurlDetails;

export type GetVersionedPurlError = unknown;

export type GetPurlData = {
  path: {
    /**
     * opaque identifier for a fully-qualified PURL, or URL-encoded pURL itself
     */
    key: string;
  };
};

export type GetPurlResponse = PurlDetails;

export type GetPurlError = unknown;

export type ListSbomsData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListSbomsResponse = PaginatedSbomSummary;

export type ListSbomsError = unknown;

export type UploadSbomData = {
  body: Blob | File;
  query: {
    /**
     * Optional labels.
     *
     * Only use keys with a prefix of `labels.`
     */
    labels: Labels;
    /**
     * Source the document came from
     */
    location: string;
  };
};

export type UploadSbomResponse = unknown;

export type UploadSbomError = unknown;

export type ListRelatedSbomsData = {
  query?: {
    /**
     * Find by a ID of a package
     */
    id?: string | null;
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    /**
     * Find by PURL
     */
    purl?: Purl | null;
    q?: string;
    sort?: string;
  };
};

export type ListRelatedSbomsResponse = PaginatedSbomSummary;

export type ListRelatedSbomsError = unknown;

export type GetSbomData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: string;
  };
};

export type GetSbomResponse = SbomDetails;

export type GetSbomError = unknown;

export type DeleteSbomData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: string;
  };
};

export type DeleteSbomResponse = SbomDetails;

export type DeleteSbomError = unknown;

export type UpdateSbomLabelsData = {
  body: Labels;
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: Id;
  };
};

export type UpdateSbomLabelsResponse = void;

export type UpdateSbomLabelsError = unknown;

export type PatchSbomLabelsData = {
  body: Labels;
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>' or 'urn:uuid:<uuid>'
     */
    id: Id;
  };
};

export type PatchSbomLabelsResponse = void;

export type PatchSbomLabelsError = unknown;

export type ListPackagesData = {
  path: {
    /**
     * ID of the SBOM to get packages for
     */
    id: string;
  };
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListPackagesResponse = PaginatedSbomPackage;

export type ListPackagesError = unknown;

export type ListRelatedPackagesData = {
  path: {
    /**
     * ID of SBOM to search packages in
     */
    id: string;
  };
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    /**
     * The Package to use as reference
     */
    reference?: string | null;
    /**
     * Optional relationship filter
     */
    relationship?: Relationship | null;
    sort?: string;
    /**
     * Which side the reference should be on
     */
    which?: Which;
  };
};

export type ListRelatedPackagesResponse = PaginatedSbomPackageRelation;

export type ListRelatedPackagesError = unknown;

export type DownloadSbomData = {
  path: {
    /**
     * Digest/hash of the document, prefixed by hash type, such as 'sha256:<hash>'
     */
    key: string;
  };
};

export type DownloadSbomResponse = Blob | File;

export type DownloadSbomError = unknown;

export type ListVulnerabilitiesData = {
  query?: {
    /**
     * The maximum number of entries to return.
     *
     * Zero means: no limit
     */
    limit?: number;
    /**
     * The first item to return, skipping all that come before it.
     *
     * NOTE: The order of items is defined by the API being called.
     */
    offset?: number;
    q?: string;
    sort?: string;
  };
};

export type ListVulnerabilitiesResponse = PaginatedVulnerabilitySummary;

export type ListVulnerabilitiesError = unknown;

export type GetVulnerabilityData = {
  path: {
    /**
     * ID of the vulnerability
     */
    id: string;
  };
};

export type GetVulnerabilityResponse = VulnerabilityDetails;

export type GetVulnerabilityError = unknown;

export type DeleteVulnerabilityData = {
  path: {
    /**
     * ID of the vulnerability
     */
    id: string;
  };
};

export type DeleteVulnerabilityResponse = VulnerabilityDetails;

export type DeleteVulnerabilityError = unknown;

export type $OpenApiTs = {
  "/api/v1/advisory": {
    get: {
      req: ListAdvisoriesData;
      res: {
        /**
         * Matching vulnerabilities
         */
        "200": PaginatedAdvisorySummary;
      };
    };
    post: {
      req: UploadAdvisoryData;
      res: {
        /**
         * Upload a file
         */
        "201": unknown;
        /**
         * The file could not be parsed as an advisory
         */
        "400": unknown;
      };
    };
  };
  "/api/v1/advisory/{id}/label": {
    put: {
      req: UpdateAdvisoryLabelsData;
      res: {
        /**
         * Replaced the labels of the advisory
         */
        "204": void;
        /**
         * The advisory could not be found
         */
        "404": unknown;
      };
    };
    patch: {
      req: PatchAdvisoryLabelsData;
      res: {
        /**
         * Modified the labels of the advisory
         */
        "204": void;
        /**
         * The advisory could not be found
         */
        "404": unknown;
      };
    };
  };
  "/api/v1/advisory/{key}": {
    get: {
      req: GetAdvisoryData;
      res: {
        /**
         * Matching advisory
         */
        "200": AdvisoryDetails;
        /**
         * Matching advisory not found
         */
        "404": unknown;
      };
    };
    delete: {
      req: DeleteAdvisoryData;
      res: {
        /**
         * Matching advisory
         */
        "200": AdvisoryDetails;
        /**
         * Matching advisory not found
         */
        "404": unknown;
      };
    };
  };
  "/api/v1/advisory/{key}/download": {
    get: {
      req: DownloadAdvisoryData;
      res: {
        /**
         * Download a an advisory
         */
        "200": Blob | File;
        /**
         * The document could not be found
         */
        "404": unknown;
      };
    };
  };
  "/api/v1/importer": {
    get: {
      res: {
        /**
         * List importer configurations
         */
        "200": Array<Importer>;
      };
    };
  };
  "/api/v1/importer/{name}": {
    get: {
      req: GetImporterData;
      res: {
        /**
         * Retrieved importer configuration
         */
        "200": RevisionedImporter;
        /**
         * An importer with that name could not be found
         */
        "404": unknown;
      };
    };
    post: {
      req: CreateImporterData;
      res: {
        /**
         * Created a new importer configuration
         */
        "201": unknown;
        /**
         * An importer with that name already exists
         */
        "409": unknown;
      };
    };
    put: {
      req: UpdateImporterData;
      res: {
        /**
         * Created a new importer configuration
         */
        "201": unknown;
        /**
         * An importer with that name does not exist
         */
        "409": unknown;
        /**
         * The provided if-match header did not match the stored revision
         */
        "412": unknown;
      };
    };
    delete: {
      req: DeleteImporterData;
      res: {
        /**
         * Delete the importer configuration
         */
        "201": unknown;
      };
    };
  };
  "/api/v1/importer/{name}/enabled": {
    put: {
      req: EnableImporterData;
      res: {
        /**
         * Updated the enable state
         */
        "201": unknown;
        /**
         * An importer with that name does not exist
         */
        "404": unknown;
        /**
         * The provided if-match header did not match the stored revision
         */
        "412": unknown;
      };
    };
  };
  "/api/v1/importer/{name}/force": {
    post: {
      req: ForceRunImporterData;
      res: {
        /**
         * Updated the state
         */
        "201": unknown;
        /**
         * An importer with that name does not exist
         */
        "404": unknown;
        /**
         * The provided if-match header did not match the stored revision
         */
        "412": unknown;
      };
    };
  };
  "/api/v1/importer/{name}/report": {
    get: {
      req: GetImporterReportsData;
      res: {
        /**
         * Retrieved importer reports
         */
        "200": PaginatedImporterReport;
      };
    };
  };
  "/api/v1/organization": {
    get: {
      req: ListOrganizationsData;
      res: {
        /**
         * Matching organizations
         */
        "200": PaginatedOrganizationSummary;
      };
    };
  };
  "/api/v1/organization/{id}": {
    get: {
      req: GetOrganizationData;
      res: {
        /**
         * Matching organization
         */
        "200": OrganizationDetails;
        /**
         * Matching organization not found
         */
        "404": unknown;
      };
    };
  };
  "/api/v1/product": {
    get: {
      req: ListProductsData;
      res: {
        /**
         * Matching products
         */
        "200": PaginatedProductSummary;
      };
    };
  };
  "/api/v1/product/{id}": {
    get: {
      req: GetProductData;
      res: {
        /**
         * Matching product
         */
        "200": ProductDetails;
        /**
         * Matching product not found
         */
        "404": unknown;
      };
    };
    delete: {
      req: DeleteProductData;
      res: {
        /**
         * Matching product
         */
        "200": ProductDetails;
        /**
         * Matching product not found
         */
        "404": unknown;
      };
    };
  };
  "/api/v1/purl": {
    get: {
      req: ListPurlData;
      res: {
        /**
         * All relevant matching qualified PURLs
         */
        "200": PaginatedPurlSummary;
      };
    };
  };
  "/api/v1/purl/base": {
    get: {
      req: ListBasePurlsData;
      res: {
        /**
         * All relevant matching versionless base PURL
         */
        "200": PaginatedBasePurlSummary;
      };
    };
  };
  "/api/v1/purl/base/{key}": {
    get: {
      req: GetBasePurlData;
      res: {
        /**
         * Details for the versionless base PURL
         */
        "200": BasePurlDetails;
      };
    };
  };
  "/api/v1/purl/type": {
    get: {
      res: {
        /**
         * List of all known PURL types
         */
        "200": Array<TypeSummary>;
      };
    };
  };
  "/api/v1/purl/type/{type}": {
    get: {
      req: GetPurlTypeData;
      res: {
        /**
         * Information regarding PURLs within an type
         */
        "200": PaginatedBasePurlSummary;
      };
    };
  };
  "/api/v1/purl/type/{type}/{namespace_and_name}": {
    get: {
      req: GetBasePurlOfTypeData;
      res: {
        /**
         * Matching vulnerabilities
         */
        "200": BasePurlDetails;
      };
    };
  };
  "/api/v1/purl/type/{type}/{namespace_and_name}@{version}": {
    get: {
      req: GetVersionedPurlOfTypeData;
      res: {
        /**
         * Matching vulnerabilities
         */
        "200": VersionedPurlDetails;
      };
    };
  };
  "/api/v1/purl/version/{key}": {
    get: {
      req: GetVersionedPurlData;
      res: {
        /**
         * Details for the version of a PURL
         */
        "200": VersionedPurlDetails;
      };
    };
  };
  "/api/v1/purl/{key}": {
    get: {
      req: GetPurlData;
      res: {
        /**
         * Details for the qualified PURL
         */
        "200": PurlDetails;
      };
    };
  };
  "/api/v1/sbom": {
    get: {
      req: ListSbomsData;
      res: {
        /**
         * Matching SBOMs
         */
        "200": PaginatedSbomSummary;
      };
    };
    post: {
      req: UploadSbomData;
      res: {
        /**
         * Upload an SBOM
         */
        "201": unknown;
        /**
         * The file could not be parsed as an advisory
         */
        "400": unknown;
      };
    };
  };
  "/api/v1/sbom/by-package": {
    get: {
      req: ListRelatedSbomsData;
      res: {
        /**
         * Matching SBOMs
         */
        "200": PaginatedSbomSummary;
      };
    };
  };
  "/api/v1/sbom/{id}": {
    get: {
      req: GetSbomData;
      res: {
        /**
         * Matching SBOM
         */
        "200": SbomDetails;
        /**
         * Matching SBOM not found
         */
        "404": unknown;
      };
    };
    delete: {
      req: DeleteSbomData;
      res: {
        /**
         * Matching SBOM
         */
        "200": SbomDetails;
        /**
         * Matching SBOM not found
         */
        "404": unknown;
      };
    };
  };
  "/api/v1/sbom/{id}/label": {
    put: {
      req: UpdateSbomLabelsData;
      res: {
        /**
         * Replaced the labels of the SBOM
         */
        "204": void;
        /**
         * The SBOM could not be found
         */
        "404": unknown;
      };
    };
    patch: {
      req: PatchSbomLabelsData;
      res: {
        /**
         * Modified the labels of the SBOM
         */
        "204": void;
        /**
         * The SBOM could not be found
         */
        "404": unknown;
      };
    };
  };
  "/api/v1/sbom/{id}/packages": {
    get: {
      req: ListPackagesData;
      res: {
        /**
         * Packages
         */
        "200": PaginatedSbomPackage;
      };
    };
  };
  "/api/v1/sbom/{id}/related": {
    get: {
      req: ListRelatedPackagesData;
      res: {
        /**
         * Packages
         */
        "200": PaginatedSbomPackageRelation;
      };
    };
  };
  "/api/v1/sbom/{key}/download": {
    get: {
      req: DownloadSbomData;
      res: {
        /**
         * Download a an SBOM
         */
        "200": Blob | File;
        /**
         * The document could not be found
         */
        "404": unknown;
      };
    };
  };
  "/api/v1/vulnerability": {
    get: {
      req: ListVulnerabilitiesData;
      res: {
        /**
         * Matching vulnerabilities
         */
        "200": PaginatedVulnerabilitySummary;
      };
    };
  };
  "/api/v1/vulnerability/{id}": {
    get: {
      req: GetVulnerabilityData;
      res: {
        /**
         * Specified vulnerability
         */
        "200": VulnerabilityDetails;
        /**
         * Specified vulnerability not found
         */
        "404": unknown;
      };
    };
    delete: {
      req: DeleteVulnerabilityData;
      res: {
        /**
         * Specified vulnerability
         */
        "200": VulnerabilityDetails;
        /**
         * Specified vulnerability not found
         */
        "404": unknown;
      };
    };
  };
};
